In [1]:
import numpy as np

In [2]:
S=np.array([[1,0,0],[0,3,-1],[0,-1,3]])

In [3]:
np.linalg.eigvals(S)

array([4., 2., 1.])

In [15]:
Sp, Q = np.linalg.eig(S)

In [16]:
Q

array([[ 0.        ,  0.        ,  1.        ],
       [-0.70710678,  0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [17]:
Sp

array([4., 2., 1.])

In [21]:
np.dot(Sp,Q)

array([-0.70710678,  2.12132034,  4.        ])

In [26]:
np.linalg.inv(Q)

array([[-0.        , -0.70710678,  0.70710678],
       [ 0.        ,  0.70710678,  0.70710678],
       [ 1.        ,  0.        ,  0.        ]])

Following result is what we want

In [31]:
np.dot(Q.T,np.dot(Sp,Q))

array([ 1.32842712,  4.32842712, -0.70710678])